[package]
name = "mci"
version = "0.0.0"
authors = ["Michael van Niekerk <mvniekerk@chazaqdev.com>"]
edition = "2018"
repository = "https://github.com/mvniekerk/mci-rs"
description = "MultiMedia Card Interface implementation using MCI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "~0.10"

[features]
sdio = []
mmc = []
default = ["sdio", "mmc"]